### ISSUE TITLE
COL - Set up Sendgrid Account

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/cost-of-living-support#18]
**Summary**
We need to set up a Sendgrid account and udapte to work with CoL

**Criteria**

- [x] Create Sendgrid account using Hyde's CoL email and put into spreadsheet 
- [x] Add the templates for the emails that already exist (e.g. Forget password)
- [x] Update the ids in the codebase to match the new template ids

**Comment by egasparini** [comment]
@maggiehoughton 
We are about to set up the Sendgrid account and we need to know which email address we should use. 
When we set up the account you will receive an email to confirm account creation, just as a heads up - can you please approve it once you receive it?
If you can please let us know here on GitHub when it's approved, so @Israa91 knows that she can continue with this task.

Thank you!

**Comment by maggiehoughton** [comment]
coldigital@hyde-housing.co.uk 
I'll look out for it.

**Comment by Israa91** [comment]
Hey @maggiehoughton thanks for your reply.
There are some questions if you can answer them, so I can go continue with creating the account ,
if the screenshot is not pefect for you I can write down the questions.
![image](https://user-images.githubusercontent.com/54477709/203291242-542b9b08-63bb-4d0a-bff4-8853694c2b0e.png)

**Comment by maggiehoughton** [comment]
Maggie Houghton
The Hyde Group 
www.hyde-housing.co.uk
+44 800 3 282 282
Other
0-100,000
1,001-5,000

**Comment by Israa91** [comment]
Thanks @maggiehoughton ,did you recieve any emails from sendgrid at this email [coldigital@hyde-housing.co.uk](mailto:coldigital@hyde-housing.co.uk) ?

**Comment by maggiehoughton** [comment]
"Thanks for contacting Twilio Support for your SendGrid inquiry. We strive to provide excellent service, and will respond to your request as soon as possible, based on perceived priority. "

I'll monitor the account for updates.

**Comment by Israa91** [comment]
Thanks @maggiehoughton ,I'll pause on this until you hear back from SendGrid.

**Comment by maggiehoughton** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/mh34/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/mh34/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/mh34/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/mh34/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-GB link=blue vlink="#954F72" style='tab-interval:36.0pt;
word-wrap:break-word'>




  | Jess (SendGrid)    Nov 22, 2022, 10:37 AM PST    Hello Maggie,       Thank you for reaching out to Consumer Trust Support. I’m Jessica, and I’m   happy to assist you with your account.       To provide some context, new sign-up requests trigger a verification process.   As a result, your account has been placed on a temporary hold so that we can   conduct this review. Our intention is to ensure that all new users intend to   utilize Twilio SendGrid in alignment with our Acceptable   Use Policy and Email   Policy.       To have your account   reviewed, please provide the following information:       1.  Intended Use   Case       ·         A complete description of the services/products your   organization provides to better understand the nature of your business.       2.   Email Type   ·         Will you be using our free one-click   unsubscribe feature as an opt-out method or do you have a method of your   own? If the latter, please include links to the website/URL or screenshots of   the unsubscribe link in your marketing email draft.       ·         How will your recipient's email addresses be collected (opt-in)?   Please provide a link to an accessible website for your organization or a   screenshot of the registration flow. If the website is not publicly available   yet, a mock-up of the sign-up page will suffice.       Please respond to this request at your   earliest convenience. We definitely understand how getting your account up   and running is important to you, and providing detailed information will help   speed up the process.       Thank you for your contribution. We're excited to see what you build!   Jessica C. \|   Consumer Trust Support   Twilio   Acceptable Use Policy
-- | --





</body>

</html>

**Comment by Israa91** [comment]
Hey @maggiehoughton do you feel comfortable to answer thses questions?

**Comment by maggiehoughton** [comment]
I can answer 1 but not 2?

**Comment by Israa91** [comment]
Hey @maggiehoughton ,for the part of mock up of signup flow, you can use these screenshots
![image](https://user-images.githubusercontent.com/54477709/203555455-f351384a-4cdb-4da2-bae1-7d6f2d2f9f82.png)
![image](https://user-images.githubusercontent.com/54477709/203555568-729a35de-803f-4b4d-a95a-ccd0fb2778a9.png)

- Will you be using our free one-click unsubscribe feature as an opt-out method or do you have a method of your own?
I think we will use SendGrid unsubscribe feature, because we don't have such feature in the app , @egasparini can you clarify this point please.

- Email type : I'm not sure about this, @egasparini  can you take a look please .

**Comment by egasparini** [comment]
@Israa91 & @maggiehoughton - Yes, we will be using their free one-click unsubscribe feature as an opt-out method.

**Comment by maggiehoughton** [comment]
Great-i've responded.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by maggiehoughton** [comment]
Should be activated now.

**Comment by Israa91** [comment]
Hi @maggiehoughton , I will use this email [coldigital@hyde-housing.co.uk](mailto:coldigital@hyde-housing.co.uk) as a sender for the sendgrid templates, you should be recieved verification email on this email ,can you verify please? thanks.

**Comment by maggiehoughton** [comment]
it's set u to send a code to another number,, can it be reset to mine? UK 0773 3887 132

**Comment by maggiehoughton** [comment]
Or just share code here if it's yours?

**Comment by Israa91** [comment]
Sorry @maggiehoughton ,let's  ignore this for now ,I will use Domain auth instead ,thanks.

**Comment by Israa91** [comment]
Hi @maggiehoughton ,last step in setting up sendgrid account is to add sender email .I added this  coldigital@hyde-housing.co.uk
but got this message 
>To verify sender identity, check your inbox at coldigital@hyde-housing.co.uk.

can you check if you got email from sendgrid please,thanks.

**Comment by Israa91** [comment]
Hi @maggiehoughton sorry for this ,but it seems that the verification failed. I resend a verification email to the same email.
Please let me know here if they asked you to enter a code or something I can send this for you.Thanks.

**Comment by maggiehoughton** [comment]
Hi they've asked for the code sent to mobile?

**Comment by Israa91** [comment]
Hey @maggiehoughton this is the code 1664875

**Comment by maggiehoughton** [comment]
I asked for resend as did not accept first code

**Comment by Israa91** [comment]
2866919  @maggiehoughton

**Comment by maggiehoughton** [comment]
Not working. Do we have a separate sendgrid account for coldigital@hyde-housing.co.uk? I only have the password for the ucdigital log in.

**Comment by maggiehoughton** [comment]
Found it

**Comment by maggiehoughton** [comment]
@Israa91 did you get another code?

**Comment by Israa91** [comment]
@maggiehoughton oh sorry thats my bad ,I forget to send you the user name and password
username : coldigital@hyde-housing.co.uk
password: a8BKv0JDLqQ61a8BKv0JDLqQ61

**Comment by Israa91** [comment]
@maggiehoughton 9475774

**Comment by maggiehoughton** [comment]
![image](https://user-images.githubusercontent.com/87085813/206438224-57fc8ebb-5bfc-482e-aa52-7ce40100b083.png)
