### ISSUE TITLE
UC Helper Deployment

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#226]
### Summary
This issue is to deploy UC Helper to production.

### Criteria
@RamyAlshurafa can you add more here as needed, please?
It may be that some of the things below are not relevant for UC Helper. I got them from #15. Feel free to remove them.

- [x] Deploy UC Helper to production
    - [x] Be aware that this is an existing product! We may need to do a DB migration before hand.  
- [x] Ensure all third party solutions are set up and working with the production version
    - [x] Google Analytics
    - [x] Hotjar
    - [x] Sendgrid
    - [x] BetterUptime
- [x] ReadMe up to date @cemalokten 
- [x] DB schema up to date in Technical Design doc 

Please, check in with @cemalokten to see the status of his latest PRs, in case they can also be included in the deployment.

**Comment by remaininlight** [comment]
Unable to access Google Analytics due to text message verification going to a number ending in 32

Unable to access Sendgrid due to text message verification being required

Unable to access Better Uptime - it isn't on the credentials sheet

Unable to access the original UC Helper DB schema (Located here I think https://www.notion.so/8169f65c04664f75839f678143559cd1) to copy it to CoL Notion and check against current version:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/4106946/217043366-f3f28d1a-6b41-4ae5-8c13-34bf6facd4a8.png">

**Comment by thejoefriel** [comment]
Have logged into Google Analytics using the details shared in the #20 issue to log in - all seems to be working and registering users daily

Have checked https://yalla.betteruptime.com/ and can confirm we are tracking UC Helper site is live

**Comment by thejoefriel** [comment]
@remaininlight the updated schema for UC Helper can be found in the Tech Stack document in the Notion workspace: https://www.notion.so/yallacooperative/Tech-Stack-External-Services-Deployment-Recommendation-v-2-0-49f58ff6d660435e8b44ac962e46fa2f

So I think it's just a quick check this is still in line with the schema following development? If not, if you can quickly tweak and confirm once done here please

**Comment by jema28** [comment]
Note: checked with Mark and the notion link in the first comment is outdated. The one in Joe's comment is the correct one

**Comment by remaininlight** [comment]
Added tables to the diagram:
common_i18n
common
organisations_resources
organisations_sections_orders
sections_i18n
topics
topics_i18n
