### ISSUE TITLE
Issue with Bold text in custom section tips

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#235]
**Summary**
2 things: 

1. You can see below that when I make some text bold in the tips the formatting is not displayed correctly on the front end. https://staging.col-helper.co.uk/erica/sections/15

2. On dark blue tip boxes, the text should always be white - not sure why the first line is not.

![Image](https://user-images.githubusercontent.com/55511970/212674275-0935f594-a74a-4da2-8209-45bd553c6a0f.png)

**Comment by cemalokten** [comment]
@egasparini The issue is caused when using the `<strong>` tag with a `-` directly before it, so `-<strong>`. If a space is added between the two it works, so `- <strong>`.

I can't replicate the second issue.

A better approach is not to use `<strong>` but to instead use the built-in editor or use `**word**`
