### ISSUE TITLE
Update Google Analytics

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/cost-of-living-support#262]
Google Analytics is due to deprecate UA (in favour of GA4) on 1st July https://support.google.com/analytics/answer/11583528?hl=en#:~:text=Google%20Analytics%204%20is%20our,4%20as%20soon%20as%20possible.

Before that we need to update Google Analytics so we're using GA4 rather than UA.

**Team - do not edit**
@thejoefriel
@dupreesi 
@Ibrahim-Jarada

**Comment by cyberteenie** [comment]
Just noting that this currently is not receiving any data. Not sure if this will be resolved with the open PR, but noting it to keep an eye open.


![Image](https://github.com/yalla-coop/cost-of-living-support/assets/97453274/1b698059-db7f-41a8-abf3-4091b0655a5d)

**Comment by cyberteenie** [comment]
Open this to double check in GA as I am confused by what I see when I open the account

**Comment by thejoefriel** [comment]
Hey, I've opened it up and once Simon deployed the fix yesterday it looks good. Snapshot here.

On this @cyberteenie it means hyde will need to be updated to check these going forward (rather than the old accounts I showed in the tutorial videos I recorded)

![image](https://github.com/yalla-coop/cost-of-living-support/assets/19708921/4683a142-b8f4-444e-81f6-9eb240e38ae6)

**Comment by lucynorgate** [comment]
Hi - just looking at the updated GA pages (the ones labelled GA4 - the COL one looks good, but the UC one looks like there is no data - from scrolling up I think you had flagged this issue, but is the UC one due to be looked at? I need to send the June report to the GAL next week, so just wondering if the data will be there by then? Thanks

**Comment by lucynorgate** [comment]
Also, is the COL GA4 pages only pulling data from June onwards? To do any year to date analysis going forward, will I be able to do that?

**Comment by thejoefriel** [comment]
Hi @lucynorgate yeah annoyingly Google is making people switch the property so the data on the GA4 side will only be from the date you see the usage begin. For any data before that you need to use the original Google Analytics.

**Comment by thejoefriel** [comment]
We're looking into the UC Helper one and will update you asap.

**Comment by lucynorgate** [comment]
> Hi @lucynorgate yeah annoyingly Google is making people switch the property so the data on the GA4 side will only be from the date you see the usage begin. For any data before that you need to use the original Google Analytics.

Yeah, that is annoying of them. Also, I may need some help relearning how to use it, although i think its possibly a bit more straight forward. I'll do some work on it on Monday and give you a shout if theres any of the reporting I can't find. Thanks
