### ISSUE TITLE
betteruptime investigation

### ISSUE THREAD

**Issue by bethanyios** [yalla-coop/cost-of-living-support#289]
Reported 99.8343% for August so will look into the details and report back

**Comment by RamyAlshurafa** [comment]
Hey @bethanyios 
- Heroku makes a backup of the DB every night, which makes the app slower in response (that happens when there are no people normally use the app)
- Sometimes the app takes some time to deploy and to be up again and that takes some time, (we normally deploy out of working hours, unless it's a hotfix)

**Comment by bethanyios** [comment]
Thank you for this update @RamyAlshurafa
