### ISSUE TITLE
duplicate tiles showing

### ISSUE THREAD

**Issue by Katie-Hyde** [yalla-coop/cost-of-living-support#307]
### Please select the priority level by adding one of the following labels to this issue?

Priority-3 (Normal e.g. Functionality is not working for a subset of users)

### Describe the bug and the expected behaviour.

duplicate tiles showing on A2 dominion version (not on Hyde's) 
![Web capture_15-1-2024_91346_col-helper co uk](https://github.com/yalla-coop/cost-of-living-support/assets/87085422/32124aab-d7d6-4ddd-9f02-61ed55a32c9b)

### Screenshots or a link to a Loom Recording

![Web capture_15-1-2024_91346_col-helper co uk](https://github.com/yalla-coop/cost-of-living-support/assets/87085422/60da9469-2a9b-4730-a257-b1cd57664fcc)

**Comment by cyberteenie** [comment]
Hi @Katie-Hyde - we are looking into why this might be! Will send an update as soon as this is fixed.

**Comment by RamyAlshurafa** [comment]
Hey @Katie-Hyde 
this is fixed now, can you check please?

**Comment by cyberteenie** [comment]
Hi @Katie-Hyde - just wanted to check to see if this issue was ready to be closed now? Thanks!

**Comment by HYDETS38** [comment]
Hi Kristina,

Hope you are keeping well. I have checked the A2 Dominion page and the issue seems to have been resolved.
The ticket can now be closed.

Hope this helps.

Tomi Stan
Money & Debt Specialist MIMA (Cert)
Debt Relief Order Intermediary
Advice & Advocacy Service
Hyde Group


T: 01243 813 803
M: 0758 777 42 85
E: ***@***.******@***.***>

Hyde Foundation * Martlet House * Southern Gate * Chichester * PO19 8SG
www.hyde-housing.co.uk<http://www.hyde-housing.co.uk/>

Hyde Housing Association is authorised by the FCA firm number 715110
MyAccount - manage your account online anywhere, anytime<https://www.hyde-housing.co.uk/tenants/myaccount/>
UC helper<https://www.uc-helper.co.uk/hyde-housing> - a step-by-step guide to applying for Universal Credit
Cost of living helper<https://col-helper.co.uk/hyde-housing> - help and support at your fingertips

Follow us: Twitter<https://twitter.com/HydeHousing> * Facebook<http://www.facebook.com/HydeGroup> * LinkedIn<http://www.linkedin.com/company/the-hyde-group> * YouTube<http://www.youtube.com/user/TheHydeGroup?feature=watch>



P Before you print think about the environment.

The information contained in this message is confidential and intended for the addressee only, this e-mail does not, nor is it intended to be, contractual in effect. If you have received this message in error unauthorised use, disclosure, copying or alteration of this message is strictly prohibited. This e-mail and any attachments have been scanned for viruses prior to leaving the Hyde Group network, we advise you to carry out your own virus checks on any attachment to this message.  Hyde Group will not be liable for direct,  indirect or consequential damages arising from alteration of the contents of this message by a third party or as a result of any virus being passed on. Hyde Group reserves the right to monitor and record e-mail messages sent to and from this address for the purposes of detecting or investigating any unauthorised use of its system and ensuring its effective operation.

**Comment by cyberteenie** [comment]
Great thank you!
